name: Testing in dev environment
on:
  push:
    branches:
      - dev
  workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Adjust the version to your needs
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-module-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm install

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' 
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: dep-node-module-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build
  
