name: Testing in dev environment
on:
  push:
    branches:
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '14.x' # Adjust the version to your needs

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build
