name: testing node app
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install node version
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'  # Choose the version you need, e.g., '16.x'
      - name: build
        run: npm install
      - name: build-2
        run: npm run build
      - name: start node application
        run: npm start
        background: true
      - name: Wait for Ngrok to start
        run: sleep 5
      - name: Get Ngrok URL
        run: curl http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url
        id: ngrok
      - name: Print Ngrok URL
        run: echo "Ngrok URL: ${{ steps.ngrok.outputs.ngrok-url }}"
