name: testing node app
on: workflow_dispatch
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: Install node version
      uses: actions/setup-node@v4
      with:
        node-version: [ 6, 14, 16, 17 ]
    - name: build
      run: npm install
    - name: build-2
      run: npm run build
    - name: start node application
      run: npm start

     