name: Deploy Node.js App with NGINX

on:
  push:
    branches:
      - prod
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Install dependencies
        run: npm install

      - name: Build Node.js app
        run: npm run build
        
      - name: start app
        run: npm start

     
