name: SonarQube-code-testing
on: 
 push:
  branch:
   - dev
   - stage
   - prod

jobs:
  SonarQube:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4

    
     - name: set up Sonarqube 
       uses: sonarsource/sonarcloud-github-action@master
       env:
           GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

       with:
          args: >
             -Dsoanr.organization=Omer Mohammed
             -Dsonar.projectKey=GITHUB-
